name: rebornUtilsPaper
version: '1.0-SNAPSHOT'
main: ru.komap.rebornUtilsPaper.RebornUtilsPaper
api-version: '1.21'

commands:
  me:
    description: Default minecraft me
    usage: /me <action>
  try:
    description: Try to do something!
    usage: /try <action>
  disaster:
    description: Summons disaster
    usage: /disaster
  minusfps:
    description: aboba
    usage: /minusfps <player>
  togglelink:
    description: aboba
    usage: /togglelink
  giveExplodingArrow:
    description: give explode arrow
    usage: /giveExplodeArrow